---
name: Test Run for github actions

run-name: ${{ github.actor }} is learning GitHub Actions

env:
  CI: false

on:
  push:
    branches:
      - "github-actions"

jobs:
  test-github-actions:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "github-actions"

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - run: yarn install
      - run: yarn build
      - run: |
          echo "${{ secrets.TEST_DIGITALOCEAN_SERVER_KEY }}" | base64 -d > server_key.pem
          chmod 0400 server_key.pem
          ls
          scp -i 'server_key.pem'  -o StrictHostKeyChecking=no -r ./build/* root@64.227.143.116:/var/www/html/monstor/
